[package]
name = "acton-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
acton-reactive = {version = "1.3.0"}
tokio = "1.45.0"
mti = {version = "1.0.0", features = ["serde"]}
acton-ern = { version = "1.1.3", features = ["serde"] }
anyhow = "1.0.98"
dashmap = "6.1.0"
rig-core = { version = "0.12.0", features = ["reqwest-rustls", "derive", "rayon"] }
